# Generated by Django 5.0.4 on 2024-05-22 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nickname',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='club',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='grade',
            field=models.TextField(null=True),
        ),
    ]
