# Generated by Django 5.0.4 on 2024-04-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_blog_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='weather',
            field=models.CharField(default='', max_length=30),
        ),
    ]
