# Generated by Django 5.0.4 on 2024-05-22 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_comment_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='tags',
        ),
    ]
